### ISSUE TITLE
libmnl.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by lebel** [jdoss/atomic-wireguard#10]
I have the following problem when I try wg:
````
↱ lebeld@tardis
↳ sudo wg                                                                                                                                                                      
/usr/bin/wg: error while loading shared libraries: libmnl.so.0: cannot open shared object file: No such file or directory

↱ lebeld@tardis 
↳ 
````
The tunnel doesn't work either, most likely because of the same error.

**Comment by jdoss** [comment]
Hey @lebel did you figure out your issue? If not, what version of WireGuard are you running in `/etc/sysconfig/atomic-wireguard` and what is your OS?

**Comment by lebel** [comment]
The latest update works! Thanks!

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by jdoss** [comment]
Wonderful! Open a new issue if you see anything else weird.

**Comment by shadowofsilicon** [comment]
I've been able to work around the issue in #14, but now I get this issue.  Any ideas?  Thank you!
