### ISSUE TITLE
how to create a wireguard killswitch for firewalld?

### ISSUE THREAD

**Issue by rugabunda** [jdoss/atomic-wireguard#11]
According to Mullvad's tutorial, to enable the killswitch for Wireguard involves the following:

A: Add the following lines under the [Interface] section of the WireGuard configuration files found in /etc/wireguard/ :

PostUp  =  iptables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PreDown = iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show  %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -D OUTPUT ! -o %i -m mark ! --mark $(wg show  %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT

CentO/S and Fedora use FirewallD in place of IPtables, thus using the rules above results in an unresponsive 'up' tunnel. What is the exact FirewallD equivalent for the rules above?

**Comment by jdoss** [comment]
Hey @rugabunda I am not sure of the exact equivalent for the above iptables rules for Firewalld, but I would check out using their Rich Language for doing what you are trying to do.

https://firewalld.org/documentation/man-pages/firewalld.richlanguage.html
https://fedoraproject.org/wiki/Features/FirewalldRichLanguage

**Comment by rugabunda** [comment]
Thank you jdoss, I will take a closer look.

**Comment by jdoss** [comment]
Cool sounds good @rugabunda post your results here if you figure it out so other users can see it too.
