### ISSUE TITLE
Can't build Silverblue 29

### ISSUE THREAD

**Issue by p1u3o** [jdoss/atomic-wireguard#12]
I am guessing this might be a configuration issue my side, but on a clean Silverblue 29 install I can't get the module to compile and install.

I've attached the log from manually running sudo atomic-wireguard-module build. It ends with this error.

> error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f29container FGC=f29 FBR=f29] Command:run Args:[KERNELDIR=/usr/lib/modules/${WIREGUARD_KERNEL_VERSION}/build make -j$(nproc) && make install] Flags:[] Attrs:map[] Message:RUN KERNELDIR=/usr/lib/modules/${WIREGUARD_KERNEL_VERSION}/build make -j$(nproc) && make install Original:RUN KERNELDIR=/usr/lib/modules/${WIREGUARD_KERNEL_VERSION}/build make -j$(nproc) && make install}: error while running runtime: exit status 2

[xvuAMASn.txt](https://github.com/jdoss/atomic-wireguard/files/2930081/xvuAMASn.txt)

**Comment by jdoss** [comment]
Hey @ChocolateMilkGod sorry for the delay on this. I just started looking into it on my Fedora 29 workstation with the older version of WireGuard that is set as default in this repo without issue. Bumping my `/etc/sysconfig/atomic-wireguard` to the most current version:

```
WIREGUARD_PRUNE_OLD_VERSIONS=false
WIREGUARD_SHA256=fcdb26fd2692d9e1dee54d14418603c38fbb973a06ce89d08fbe45292ff37f79
WIREGUARD_VERSION=0.0.20190227
```
and I am seeing the same thing. I'll work on seeing if I can track down the problem and get a patch submitted.

**Comment by zx2c4** [comment]
Can you send more of the build log?

**Comment by zx2c4** [comment]
First:

```
STEP 12: RUN dnf update -y && dnf install         libmnl-devel elfutils-libelf-devel findutils binutils boost-atomic boost-chrono         boost-date-time boost-system boost-thread cpp dyninst efivar-libs gc         gcc glibc-devel glibc-headers guile koji isl libatomic_ops libdwarf libmpc         libpkgconf libtool-ltdl libxcrypt-devel make mokutil pkgconf pkgconf-m4         pkgconf-pkg-config unzip zip /usr/bin/pkg-config xz -y &&         koji download-build --rpm --arch=x86_64 kernel-core-${WIREGUARD_KERNEL_VERSION} &&         koji download-build --rpm --arch=x86_64 kernel-devel-${WIREGUARD_KERNEL_VERSION} &&         koji download-build --rpm --arch=x86_64 kernel-modules-${WIREGUARD_KERNEL_VERSION} &&         dnf install kernel-core-${WIREGUARD_KERNEL_VERSION}.rpm         kernel-devel-${WIREGUARD_KERNEL_VERSION}.rpm         kernel-modules-${WIREGUARD_KERNEL_VERSION}.rpm -y &&         dnf clean all &&         curl -LS https://git.zx2c4.com/WireGuard/snapshot/WireGuard-${WIREGUARD_VERSION}.tar.xz |         { t="$(mktemp)"; trap "rm -f '$t'" INT TERM EXIT; cat >| "$t"; sha256sum --quiet -c <<<"${WIREGUARD_SHA256} $t"         || exit 1; cat "$t"; } | tar xJf -
``

Later:

```
STEP 16: RUN KERNELDIR=/usr/lib/modules/${WIREGUARD_KERNEL_VERSION}/build make -j$(nproc) && make install
```

Perhaps you need `cd src` in there? Or `cd WireGuard-$version/src`? Or something to that extent?

**Comment by jdoss** [comment]
That is odd. https://github.com/jdoss/atomic-wireguard/blob/master/Dockerfile#L27 should handle moving to `/tmp/WireGuard-${WIREGUARD_VERSION}/src`. I threw a pwd into the Docker file and the `${WIREGUARD_VERSION}` var is no longer being expanded by WORKDIR. It works fine with `cd /tmp/WireGuard-${WIREGUARD_VERSION}/src`.

**Comment by jdoss** [comment]
@ChocolateMilkGod Can you try the most recent release and let me know if you are still having issues?
