### ISSUE TITLE
Cannot build on Fedora Silverblue 30

### ISSUE THREAD

**Issue by shadowofsilicon** [jdoss/atomic-wireguard#14]
I am unable to build the wireguard kernel module on Fedora Silverblue 30.

It appears to be an issue with the checksum after it downloads the wireguard package:

`sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

Interesting, the build will complete successfully when I download the Dockerfile to my system, then run the `podman build` command from the `atomic-wireguard-module` script.

Here is a [link](https://1drv.ms/t/s!AilSk027aY9KjpQ1O_u1TKac5r2xtw) to the output of `atomic-wireguard-module build`
Thank you!

**Comment by Anth0rx** [comment]
I get the exact same error.

**Comment by jdoss** [comment]
It looks like it is not getting the env var for the checksum from `/etc/sysconfig/atomic-wireguard`. Can you temporarily turn off SELinux `sudo setenforce 0` and then `sudo systemctl stop atomic-wireguard` and then `sudo systemctl start atomic-wireguard` and see if it builds correctly? In another terminal you can run `sudo journalctl -f -u atomic-wireguard` to follow the logs and see them as it builds.

Don't forget to turn SELinux back on afterwards with `sudo setenforce 1` 

I don't have a laptop I can install Silverblue on so my troubleshooting is going to be depend on your feedback. Thanks for opening this issue.

**Comment by Anth0rx** [comment]
So, I have tried rebuilding atomic-wireguard with `atomic-wireguard-module reload` and SELinux turned off but still got the error above.

**Comment by jdoss** [comment]
@Anth0rx What is in your `/etc/sysconfig/atomic-wireguard` file?

**Comment by Anth0rx** [comment]
WIREGUARD_PRUNE_OLD_VERSIONS=false
WIREGUARD_SHA256=2f06f3adf70b95e74a7736a22dcf6e9ef623b311a15b7d55b5474e57c3d0415b
WIREGUARD_VERSION=0.0.20190406

**Comment by shadowofsilicon** [comment]
I believe I see the problem.  The atomic-wireguard-module script is not reading the environment variables.

I added the following line at the beginning of atomic-wireguard-module and the module built successfully.

`source /etc/sysconfig/atomic-wireguard`

**Comment by jdoss** [comment]
Fixed with https://github.com/jdoss/atomic-wireguard/pull/16

**Comment by jdoss** [comment]
@shadowofsilicon https://copr.fedorainfracloud.org/coprs/jdoss/atomic-wireguard/build/969788/ should be done building soon if you can test it out.
