### ISSUE TITLE
Silverblue 29 beta is upon us!

### ISSUE THREAD

**Issue by lebel** [jdoss/atomic-wireguard#7]
Right now, I can't use this solution with version 29 of Silverblue (or version 29 of Atomic Host I guess too).

Will you provide a repo for 29 too?

**Comment by jdoss** [comment]
Hey @lebel I have rebuilt the current release with a Fedora 29 repo. https://copr.fedorainfracloud.org/coprs/jdoss/atomic-wireguard/build/801277/ Can you give this a try?

**Comment by lebel** [comment]
I had to "start" the atomic-wireguard twice to have it complete successfully­. First time it got killed by systemd for taking too long, or something to that extent.

    [I] (VEnv) [13:12] lebel@silverblue:~
    $ lsmod|grep wireguar
    wireguard             229376  0
    ip6_udp_tunnel         16384  1 wireguard
    udp_tunnel             16384  1 wireguard
    [I] (VEnv) [13:12] lebel@silverblue:~
    $

**Comment by jdoss** [comment]
Cool. There are prob a few edge cases that need some work. If you can narrow it down to a specific problem, open a new GH issue.
